# Generated by Django 3.2.3 on 2021-05-13 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='group',
            new_name='name',
        ),
    ]
