# Generated by Django 3.2.3 on 2021-05-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_group_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='group',
            new_name='category',
        ),
    ]
